name: Deploy Application
on:
  push:
    branches:
      - master
      - feature/issue-20-build-app

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        env:
          VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
        with:
          cmd: build # will run `yarn build` command

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist

      - name: Prepare SSH key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PKEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Copy project files
        run: |
          ls -lah deploy_dist/

      - name: Copy project files1
        run: |
          scp -v -o StrictHostKeyChecking=no -r ./deploy_dist ${{ secrets.SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:${{ secrets.PROD_PROJECT_ROOT }}
