name: Deploy Application
on:
  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker
        run: docker build -t podcast-ui --file etc/Dockerfile  .

      - name: Build App
        run: | 
          docker run --rm --volume ./dist:/podcast-ui/dist \
          --env VUE_APP_API_URL=${{ secrets.VUE_APP_API_URL }} \
          --env VUE_APP_WS_URL=${{ secrets.VUE_APP_WS_URL }} \
          podcast-ui

      - name: Test
        run: |
          ls -lah ./dist
          if [ -z "$(ls -A ./dist)" ]; then
             echo "Dist directory is empty"
             exit 1
          else
             echo "Dist was built"
          fi

      - name: Prepare SSH key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PKEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Copy project files
        run: |
          scp -o StrictHostKeyChecking=no -r ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:${{ secrets.PROD_PROJECT_ROOT }}
