name: Deploy Application
on:
  push:
    branches:
      - master
      - tech/123-fix-building

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command

      - name: Build
        uses: borales/actions-yarn@v3.0.0
        env:
          VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
          VUE_APP_WS_URL: ${{ secrets.VUE_APP_WS_URL }}
        with:
          cmd: build # will run `yarn build` command
#
#      - name: Archive build (crating artifacts)
#        if: success()
#        uses: actions/upload-artifact@v1
#        with:
#          name: deploy_dist
#          path: dist
#
#      - name: Download and unzip build
#        uses: actions/download-artifact@v1
#        with:
#          name: deploy_dist
#
#      - name: Prepare SSH key
#        run: |
#          mkdir ~/.ssh
#          echo "${{ secrets.SSH_PKEY }}" > ~/.ssh/id_rsa
#          chmod 400 ~/.ssh/id_rsa
#
#      - name: Copy project files
#        run: |
#          scp -o StrictHostKeyChecking=no -r ./deploy_dist/* ${{ secrets.SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:${{ secrets.PROD_PROJECT_ROOT }}
