name: Test Build Application
on:
  pull_request:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker
        run: docker build -t podcast-ui --file etc/Dockerfile  .

      - name: Build App
        run: docker run --rm --volume ./dist:/podcast-ui/dist podcast-ui

      - name: Test
        run: |
          ls -lah ./dist
          if [ -z "$(ls -A ./dist)" ]; then
             echo "Dist directory is empty"
             exit 1
          else
             echo "Dist was built"
          fi
